### ISSUE TITLE
Add item durability to configuration 

### ISSUE THREAD

**Issue by raiponz** [OnapleRPG/Itemizer#1]
I could be interesting to add the item durability (max and current) to item configuration.

**Comment by zessirb** [comment]
Item durability has already been added, I updated the readme file.
However, the max durability doesn't seem to be possible with Sponge : the data manipulator for durability only contains the current durability and the unbreakable attribute. Closing for now.

**Comment by raiponz** [comment]
the fonctionality works? the last time I tested it this was not functional

**Comment by zessirb** [comment]
It works with the key word "durability", I just tested it, but only if you specify a value that is consistent with the item (a wooden sword won't allow a 2000 durability)
