### ISSUE TITLE
[REQUEST] Allow retrieval of a specified quantity of items

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Itemizer#12]
Add the ability to retrieve a quantity of items specified at the end of the command (defaults to 1)
sp `/retrieve 22` will give you 1 of 22 `/retrieve 22 10` would give you 10 of 22

**Comment by zessirb** [comment]
This might be useful indeed - this is now in [the new release](https://github.com/OnapleRPG/Itemizer/releases/tag/1.5.4).
