### ISSUE TITLE
[BUG] Itemizer 1.5.4 and Harvester 1.2 conflict and crash

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Itemizer#13]
The latest release of Itemizer 1.5.4 and Harvester 1.2 are begin registered as the same mod/plugin and crashing on load.

Log: https://pastebin.com/SXeT0uj8

**Comment by raiponz** [comment]
It's weird, 
can you try to downloads plugin again and retry. if the problem still occur, send me your mcmod.info files (in plugin java archive)

**Comment by raiponz** [comment]
Forget what I said, the problem is solved in the 1.5.5

**Comment by zessirb** [comment]
Somehow a very old version of Harvester was found in the release jar. I don't have the explanation of how it happened, but it's probably on my side. I removed it from the jar.  
Sorry for the inconvenience.
