### ISSUE TITLE
API for generating random items rather than having predefined sets

### ISSUE THREAD

**Issue by NeumimTo** [OnapleRPG/Itemizer#18]
Stuff to read:

Diablo 2
http://classic.battle.net/diablo2exp/items/magic/suf.shtml
https://diablo.gamepedia.com/Affixes_(Diablo_II)

Path of exile:
https://pathofexile.gamepedia.com/Item_affix
https://poeitem.crunchyintheory.com/#/

- Ability to predefine set of item affixes which are then randomly picked up and set to the itemstack. 

Example config:

afixes.conf
```
afixes=[
  {
  __class__: cz.neumimto.itemizer.nbt.CustomEnchantment //ItemNbtFactory class
  group: "movement"
  validItems: ["minecrafT:diamond_boots"]
  tiers: [
     {
     effects {
       IncreasedMovementSpeed: [
               value: "10%"
       ]
     }  
     suffix: "of Runner"
    prefix: null
     }
    {
     effects {
       IncreasedMovementSpeed: [
               value: "15%"
       ]
     }  
     suffix: "of Sprinter"
    prefix: null
    }
  ]
  }
]
```

such configuration could generate two items.
diamond boots with name "diamond boots of Runner" increasing player movement speed by 10%
diamond boots with name "diamond boots of Sprinter" increasing player movement speed by 15%
Adding more affixes would increase the amount of items the plugin can generate by a geometric sequence

- Each tier may have modify item name via suffix/prefix
- An item may not roll multiple tiers from one group
- Ability to restrict on which item types may the affix be applied.

**Comment by hellbringer616** [comment]
This would be an amazing feature!

**Comment by Hbeau** [comment]
The feature is done. it will be available in the next release :tada:
