### ISSUE TITLE
[REQUEST] Define a quantity to be dropped from pools.conf

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Itemizer#20]
Requesting to add the ability to define a quantity of items to be dropped from the item pool.
In this example you will drop 22 of item 1 from items.conf 20% of the time.
```
pools = [
    {
        id: 1,
        items: [
            {
                probability: 0.2,
                ref: 1
                quantity: 22
            }
        ]
    }
]
```

**Comment by Hbeau** [comment]
changes are committed to master, next release soon 😃
