### ISSUE TITLE
[REQUEST] Multiple config files

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Itemizer#22]
Would it be possible to add a folder called "items" and within that folder any .conf file can be loaded per usual? the same limitations of only allowing one ID to be allocated would apply across all configs.
for example inside of `weapons.conf` if you had an item with an ID of 11, you could not also have an item with an ID of 11 within `armor.conf`

It would make managing configs with a lot of items much easier.

My config along has over 50 items in it, and it's annoying to find things :wink: 

If the same could apply to Pools that also would be amazing!

**Comment by zessirb** [comment]
Hello @hellbringer616 ,  
Sorry the Pull Request stayed idle for so long, we now support multiple config files in Itemizer, starting with version 3.7.0.  
I had an issue with the bintray release system, so I uploaded it as [a Github release here](https://github.com/OnapleRPG/Itemizer/releases/download/3.7.1/Itemizer-3.7.1.jar).  

*Side note with the **/register** command; it does not handle the multiple config files, so when registering an item it will put it in the **items.conf** file with every other existing items. It does not break the multi-file system though, but sorry for the inconvenience*
