### ISSUE TITLE
[Question] Can multiple items be used for shapeless recipes

### ISSUE THREAD

**Issue by The-Fireplace** [OnapleRPG/Itemizer#23]
In crafts.conf, is it possible to use multiple items as the input for a shapeless recipe?

Side note, can this be used to reliably override vanilla recipes? E.g. the stairs recipe?

**Comment by Hbeau** [comment]
Hi, I m really sorry for this very late answer,I hope it s still usefull. 
1 actually it's not possible to make a shapless crafting with multiple item in Itemizer. Whereas sponge allow it so I can make the feature
2 Sadly, it s not possible to override vanilla 's crafts. 

fell free to ask any questions you have. I swear I will aswers more rapidly. you can also use our [discord](https://discord.gg/TkZWGd3)

**Comment by The-Fireplace** [comment]
No problem. I ended up coding the changes I wanted into a Forge mod.
