### ISSUE TITLE
[Question]Pixelmon Items

### ISSUE THREAD

**Issue by ShrekKid69** [OnapleRPG/Itemizer#29]
How would I use this for Pixelmon Items, like the clone machine I disabled it with mmcrestrict but I want to have a custom recipe for it using this plugin, is it possible?

**Comment by Hbeau** [comment]
Yes, it is. which version are you using ? (custom craft don't work the same way between versions)

**Comment by ShrekKid69** [comment]
I am on latest version of Itemizer with Pixelmon 7.2.2 and for some reason the custom recipe won't work, the cloning machine is restricted with mcc but the itemizer craft wont work

**Comment by Hbeau** [comment]
I have issue with 7.2 . I need to upload a new version. It will be soon

**Comment by ShrekKid69** [comment]
alrighty, cant wait! its such a unique plugin especially for modded

**Comment by Hbeau** [comment]
I released the 3.5.1 version with workings crafts. You can download from our Github main page.
 crafts keep complex to use, feel free to ask questions.
