### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ShrekKid69** [OnapleRPG/Itemizer#30]
Sorry, didnt know where to messager this too you but the latest version doesnt show on the github yet? I went to the link specified in the desc. sorry again if this is not the right way to contact.

**Comment by Hbeau** [comment]
No problems, I forgot to mention it on Github. You can join our [discord](https://discord.gg/TkZWGd3). I answers way faster. :sweat_smile:

**Comment by zessirb** [comment]
Our release system shifted from Github releases to bintray, so the correct way to find the last released version is through the README badge, sorry if this lacked of clarity
