### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by galoti** [OnapleRPG/Itemizer#6]
Hello!! Please add full support to nbtdata, I want to add player heads with texture on Itemizer. Like this one: 
   ![Desejo](https://upload.cc/i1/2018/11/01/FJpDnA.png)

  Command to add item directly from hand to the config ( like "/itemizer add" holding the item).

   And an option to disable the "Can mine:" text in the item. Example:
     ![Desabilitar](https://upload.cc/i1/2018/11/01/zcZfVN.png)

**Comment by raiponz** [comment]
Hello, thank you for your request. We are working on several improvements and we will release an update soon. It includes:

* the __can mine mention__ disappear if there is no block set

* /register command to add new item from hand.

The possibility to add custom NBT need a reflection by our side. It's our next objective 😄

**Comment by galoti** [comment]
Ok, thank you ;)

**Comment by raiponz** [comment]
Hi, I have publish a [release](https://github.com/OnapleRPG/Itemizer/releases) on github with these feature
